<a href="https://colab.research.google.com/github/andrethydavid/Archivo/blob/master/copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.



In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr [0:6]

array([0, 1, 2, 3, 4, 5])

In [6]:
arr_copy = arr.copy()

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr_copy[:] = 100

In [9]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])