<a href="https://colab.research.google.com/github/andrethydavid/Archivo/blob/master/dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [5]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [7]:
matriz = np.array([1,2,3,4,5,6])
print(matriz)
matriz.ndim

[1 2 3 4 5 6]


1

In [8]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

## Agregar o eliminar dimeciones


In [11]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10