<a href="https://colab.research.google.com/github/andrethydavid/Archivo/blob/master/el_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
 list = [1,2,3,4,5,6,7,8,9]
 list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
arr = np.array(list)

In [10]:
type(arr)

numpy.ndarray

In [12]:
from numpy.matrixlib.defmatrix import matrix
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(matrix)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr [0]

1

In [15]:
arr[0] + arr[5]

7

In [16]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
matrix[0]

array([1, 2, 3])

In [18]:
matrix[0,2]

3

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[1:5]

array([2, 3, 4, 5])

In [21]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[::2]

array([1, 3, 5, 7, 9])

In [26]:
arr[-1: ]

array([9])

In [27]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])