<a href="https://colab.research.google.com/github/andrethydavid/Archivo/blob/master/operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list = [1,2]
list

[1, 2]

In [3]:
list * 2

[1, 2, 1, 2]

In [5]:
arr = np.arange(0,10)
arr2 = arr.copy()

Operaciones

In [8]:
arr  * 2 # multiplicar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr + 2 #sumar

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
11 / arr #dicivir

<ipython-input-10-80e5028cbd4b>:1: RuntimeWarning: divide by zero encountered in true_divide
  11 / arr


array([        inf, 11.        ,  5.5       ,  3.66666667,  2.75      ,
        2.2       ,  1.83333333,  1.57142857,  1.375     ,  1.22222222])

In [11]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [16]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [17]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [20]:
np.matmul(matriz, matriz2.T) #OPERACION CON .


array([[ 30,  80],
       [ 80, 255]])

In [21]:
matriz @ matriz2.T #OPERACIONES DE .

array([[ 30,  80],
       [ 80, 255]])